//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityClient.SecurityRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SecurityRef.ISecurityService")]
    public interface ISecurityService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/GetPublicInfo", ReplyAction="http://tempuri.org/ISecurityService/GetPublicInfoResponse")]
        string GetPublicInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/GetPublicInfo", ReplyAction="http://tempuri.org/ISecurityService/GetPublicInfoResponse")]
        System.Threading.Tasks.Task<string> GetPublicInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/GetManagerSecret", ReplyAction="http://tempuri.org/ISecurityService/GetManagerSecretResponse")]
        string GetManagerSecret();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/GetManagerSecret", ReplyAction="http://tempuri.org/ISecurityService/GetManagerSecretResponse")]
        System.Threading.Tasks.Task<string> GetManagerSecretAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISecurityServiceChannel : SecurityClient.SecurityRef.ISecurityService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SecurityServiceClient : System.ServiceModel.ClientBase<SecurityClient.SecurityRef.ISecurityService>, SecurityClient.SecurityRef.ISecurityService {
        
        public SecurityServiceClient() {
        }
        
        public SecurityServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SecurityServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecurityServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecurityServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetPublicInfo() {
            return base.Channel.GetPublicInfo();
        }
        
        public System.Threading.Tasks.Task<string> GetPublicInfoAsync() {
            return base.Channel.GetPublicInfoAsync();
        }
        
        public string GetManagerSecret() {
            return base.Channel.GetManagerSecret();
        }
        
        public System.Threading.Tasks.Task<string> GetManagerSecretAsync() {
            return base.Channel.GetManagerSecretAsync();
        }
    }
}
